env:
  node: true
  jest: true
parserOptions:
  ecmaVersion: 2020
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:import/recommended'
rules:
  no-console: 0
  no-multiple-empty-lines: 1
  consistent-return: 1
  array-callback-return: [
      1,
      {
        allowImplicit: true
      }
  ]
  import/extensions: 0
  max-len: [
      1,
      {
        "code": 150,
        "ignoreComments": true
      }
  ]
  no-underscore-dangle: [
      2,
      {
        "allow": [ "__filename", "__dirname" ]
      }
  ]
plugins:
  - jest
  - babel
settings:
  import/resolver:
    node:
      extensions:
        - ".js"
