env:
  node: true
  jest: true
parserOptions:
  ecmaVersion: 2020
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:import/recommended'
  - 'plugin:fp/recommended'
plugins:
  - jest
  - babel
  - fp
rules:
  no-console: 0
  arrow-body-style: 2
  fp/no-mutating-methods: 2
  fp/no-unused-expression: 0
  fp/no-nil: 0
  no-multiple-empty-lines: 1
  consistent-return: 1
  array-callback-return: 2
  import/extensions: 0
  max-len: [
      2,
      {
        "code": 100,
        "ignoreComments": false
      }
  ]
  no-underscore-dangle: [
      2,
      {
        "allow": [ "__filename", "__dirname" ]
      }
  ]
settings:
  import/resolver:
    node:
      extensions:
        - ".js"
