name: eslint

on:
  - push

jobs:
  checkCodestyle:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Make lint
        run: |
          npm install
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
